version: "3.5"

services:
  angudock:
    container_name: angudock
    build: ./AnguDock
    image: angudock:v1.0.0
    volumes:
      - ./AnguDock:/app
      - /app/node_modules
    tty: true
    ports:
      - "4200:4200"
    command: bash -c "ng serve --host 0.0.0.0 --port 4200"

  laradock:
    container_name: laradock
    build: ./LaraDock
    image: laradock:v1.0.0
    volumes: 
      - ./LaraDock:/app
      - /app/vendor
    tty: true
    ports:
      - "8000:8000"
    depends_on:
      - mysqdock
    environment:
      - MYSQL_USER=application
      - MYSQL_PASS=devel
    command: bash -c "composer dump-autoload && php artisan serve --host 0.0.0.0 --port 8000"

  mysqdock:
    container_name: mysqdock
    build: ./MysqDock
    image: mysqdock:v1.0.0
    volumes:
      - "./MysqDock/db:/var/lib/mysql"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=devel
      - MYSQL_DATABASE=app
      - MYSQL_USER=application
      - MYSQL_PASSWORD=devel
